### ISSUE TITLE
Vote configuration editor: Roadmap

### ISSUE THREAD

**Issue by cbrzn** [dOrgTech/alchemy#3]
# Problem
Editing a DAO plugin's voting machine configuration is currently super complicated. Users do not have an easy to use interface within Alchemy for doing this.

# Solution
We want to modify the existing "plugin information" view to allow for users to make edits to the genesis protocol form, and "save" those changes to their DAO. This will prompt the users with 2 transactions:
1. Add the parameters to the voting machine.
2. Add the parameters to the scheme.
3. Create a proposal to edit the plugin being modified.

<img width="851" alt="Screenshot 2020-03-04 at 12 37 32" src="https://user-images.githubusercontent.com/21031138/75875915-ee625500-5e14-11ea-94ae-a60dfe074613.png">

# Impact
I think this is very urgent since we need to create tools to make DAOs more user-friendly. This will allow the organizations to evolve their governance post launch.

**Comment by orishim** [comment]
https://github.com/dOrgTech/Ecosystem/blob/master/proposals/Alchemy/02-voting-configuration-editor.md
